### ISSUE TITLE
ensure that raster_to_pg() is used (correctly)

### ISSUE THREAD

**Issue by kvelleby** [prio-data/priogrid#25]
I recently updated raster_to_pg() so that it calls rasterextent_to_pg() if needed. There are several places in the code where you see these being called in succession. This should be fixed (and tested). We should also ensure that raster_to_pg() is being used where it could be used. There might be older code that does not use the function.

**Comment by vildebl** [comment]
I found a small bug in raster_to_pg(): `raster::extent(rast) != priogrid::prio_extent() == FALSE` even when extents are not equal, so that rasterextent_to_pg() is not called when needed. 

The code in utility_functions is updated. I'll go through all gen_*() functions to make sure that it now works, and that only raster_to_pg() is used.

**Comment by vildebl** [comment]
All functions calling rasterextent_to_pg() have been updated to use only raster_to_pg(). All gen_*() functions that have rasters as input data are also using raster_to_pg().
